input:
  dir: "resources/input/"

# Single-end config for cutadapt.
cutadapt_se:
  extra: >-
    -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
    --minimum-length 20

# Paired-end config for cutadapt.
cutadapt_pe:
  extra: >-
    -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA
    -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
    -q 20
    --minimum-length 20

# Single-end config for cutadapt.
#cutadapt_se:
#  params:
#    adapters=" -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA",
#    extra="-q 20 --minimum-length 20"

# Paired-end config for cutadapt.
#cutadapt_pe:
#  params:
#    adapters=" -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT",
#    extra="-q 20 --minimum-length 20"

star:
  index: 'resources/references/star_Homo_sapiens.GRCh38.dna.primary_assembly_overhang50'
  readgroup: >-
    ID:{sample}.{lane} SM:{sample} LB:{sample}
    PU:{sample}.{lane} PL:ILLUMINA CN:NKI-AvL
  extra: "" # "--outSAMtype BAM Unsorted"
  threads: 10

sambamba_sort:
  extra: ''
  threads: 10

samtools_merge:
  extra: ''
  threads: 10

feature_counts:
  annotation: 'resources/references/Homo_sapiens.GRCh38.112.gtf'
  extra: ''
  threads: 5

multiqc:
  extra: ''

fastqc:
  extra: ''
